# Generated by Django 5.1.7 on 2025-03-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="roles",
            field=models.CharField(
                choices=[
                    ("admin", "ADMIN"),
                    ("librarian", "LIBRARIAN"),
                    ("member", "MEMBER"),
                ],
                default="",
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
