# Generated by Django 5.1.7 on 2025-03-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_customuser_roles"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
